version: '3.4'

services:
  sql.data:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
            SA_PASSWORD: "Nikhil@123"
            ACCEPT_EULA: "Y"
    ports:
      - "1445:1433"    
    networks:
      - aspnetcoreapp-network

  basket.data:
    image: redis:alpine
    ports:
      - "6377:6379"  
    networks:
      - aspnetcoreapp-network 

  catalog.api:
    build:
      context: Services/Catalog/Catalog.API/
      dockerfile: Dockerfile
    image : shop/catalog
    environment:
      - ConnectionString=Server=sql.data;Database=CatalogDB;User Id=SA;Password=Nikhil@123;MultipleActiveResultSets=True
      - ASPNETCORE_URLS=http://+:80
      - ExternalCatalogBaseUrl=http://localhost:5102/pics
      - AuthorityUrl=http://10.100.16.67:5101
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - 80
      - "5102:80"
    depends_on: 
      - sql.data
    networks:
      - aspnetcoreapp-network

  basket.api:
    build: 
      context: Services/Basket.API/
      dockerfile: Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development 
    image: shop/basket
    ports:
      - "5103:80"
    depends_on:
      - basket.data
    networks:
      - aspnetcoreapp-network

  identity.api:
    build:
      context: Services/Identity/Identity.API/
      dockerfile: Dockerfile
    image : shop/identity
    environment:
      - ConnectionString=Server=sql.data;Database=IdentityDB;User Id=SA;Password=Nikhil@123;MultipleActiveResultSets=True
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "5101:80"
    depends_on: 
      - sql.data
    networks:
      - aspnetcoreapp-network

  mvc.client:
    build:
      context: Web/Client/
      dockerfile: Dockerfile
    image : shop/client
    environment:
      - CatalogUrl=http://catalog.api
      - IdentityUrl=http://10.100.16.67:5101
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - 80
      - "5100:80"
    depends_on: 
      - catalog.api
      - identity.api
    networks:
      - aspnetcoreapp-network
    
   

networks:
    aspnetcoreapp-network:
        driver: bridge