version: '3.4'

services:
  catalog.api:
    image: shop/catalog:dev
    container_name: Catalog.API
    build:
      target: publishcode
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Catalog.API"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages
    volumes:
      - C:\Users\3frames-61\Desktop\eShopOnContainersReplica\src\Services\Catalog\Catalog.API:/app
      - C:\Users\3frames-61\Desktop\eShopOnContainersReplica\src\Services\Catalog\Catalog.API:/src
      - C:\Users\3frames-61\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\3frames-61\.nuget\packages\:/root/.nuget/packages:ro
      - C:\Program Files (x86)\dotnet\sdk\NuGetFallbackFolder:/root/.nuget/fallbackpackages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  \"\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true